version: '3.9'

x-env-files: &default-envs
  - ./envs/docker.env

services:

  gunicorn:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sample_py
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
    env_file: *default-envs
    ports:
      - "8000:8000"
    working_dir: /app/src
    command: ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
    profiles:
      - app

  redis:
    image: redis:3.2.6-alpine
    ports:
      - 6379:6379
    profiles:
      - infra

  postgres:
    image: postgres:11.3-alpine
    init: true
    restart: on-failure
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - 5432:5432
    expose:
      - "5432"
    env_file:
      - envs/docker.env
    profiles:
      - infra

  mongodb:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    profiles:
      - infra

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      # ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      # ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongo://mongodb:27017/
    depends_on:
      - mongodb
    profiles:
      - infra


volumes:
  mongo_data:
  local_postgres_data:
  local_postgres_data_backups:
